include(
    ":app",
    ":core:navigation",
    ":core:utils",
    ":core:rx",
    ":core:database",
    ":core:workmanager",
    ":core:resources",
    ":core:recycler",
    ":feature:home",
    ":feature:worker_price_alerter",
    ":feature:watch_list",
    ":feature:alert_log",
    ":feature:alert_log_core"
)
