include(
    ":app",
    ":core:navigation",
    ":core:utils",
    ":core:rx",
    ":core:database",
    ":core:workmanager",
    ":core:resources",
    ":feature:home",
    ":feature:worker_price_alerter",
    ":feature:stock_list",
    ":feature:alert_log"
)
